import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function ref() {
  return `REF-${Math.floor(1000 + Math.random() * 9000)}`;
}

const SEED_LISTINGS = [
  {
    ref: ref(),
    name: 'Siemens SOMATOM Definition AS+ CT Scanner',
    category: 'diagnostic-imaging',
    manufacturer: 'Siemens Healthineers',
    model: 'SOMATOM Definition AS+',
    serial: 'SH-CT-20190471',
    year: 2019,
    condition: 'used',
    warranty: 'expired',
    listingType: 'for_sale',
    price: 950000,
    currency: 'SAR',
    payment: 'bank_transfer',
    location: 'Riyadh',
    country: 'SA',
    description: 'Well-maintained 64-slice CT scanner from a major hospital upgrade. Low scan count, full service history available. Currently deinstalled and ready for relocation.',
    specs: '64-slice, 0.33s rotation time, 50cm FOV, CARE Dose 4D. Includes original console and UPS.',
    images: '[]',
    status: 'approved',
    sellerName: 'Ahmed Al-Rashid',
    sellerEmail: 'ahmed@riyadhmedical.sa',
    sellerPhone: '+966512345678',
    sellerCompany: 'Riyadh Medical Center',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'GE Healthcare Optima MR360 1.5T MRI System',
    category: 'diagnostic-imaging',
    manufacturer: 'GE Healthcare',
    model: 'Optima MR360',
    serial: 'GE-MRI-20170239',
    year: 2017,
    condition: 'refurbished',
    warranty: 'active',
    listingType: 'for_sale',
    price: 1800000,
    currency: 'SAR',
    payment: 'negotiable',
    location: 'Jeddah',
    country: 'SA',
    description: 'Fully refurbished 1.5T MRI by certified GE service center. New gradient coils installed 2023. Complete with patient table, head coil, body coil, and spine coil.',
    specs: '1.5T superconducting magnet, 33mT/m gradient, 200 T/m/s slew rate. Magnet helium refilled 2024.',
    images: '[]',
    status: 'approved',
    sellerName: 'Fatima Al-Zahrani',
    sellerEmail: 'fatima@jeddahclinic.sa',
    sellerPhone: '+966523456789',
    sellerCompany: 'Jeddah Diagnostic Clinic',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Philips IntelliVue MX800 Patient Monitor',
    category: 'patient-monitoring',
    manufacturer: 'Philips',
    model: 'IntelliVue MX800',
    serial: 'PH-MX800-20210115',
    year: 2021,
    condition: 'used',
    warranty: 'none',
    listingType: 'for_sale',
    price: 28000,
    currency: 'SAR',
    payment: 'cash',
    location: 'Dammam',
    country: 'SA',
    description: 'ICU-grade bedside monitor. Monitoring ECG, SpO2, NIBP, IBP (2 channels), EtCO2, and temperature. Excellent working condition. Selling due to fleet standardization.',
    specs: '15" touchscreen, 12-lead ECG, neonatal-adult range, LAN/WiFi connectivity.',
    images: '[]',
    status: 'approved',
    sellerName: 'Dr. Khalid Mansour',
    sellerEmail: 'k.mansour@easternhospital.sa',
    sellerPhone: '+966534567890',
    sellerCompany: 'Eastern Province Hospital',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Mindray BS-800 Biochemistry Analyzer',
    category: 'laboratory-equipment',
    manufacturer: 'Mindray',
    model: 'BS-800',
    serial: 'MR-LAB-20200344',
    year: 2020,
    condition: 'used',
    warranty: 'extendable',
    listingType: 'for_sale',
    price: 65000,
    currency: 'SAR',
    payment: 'bank_transfer',
    location: 'Riyadh',
    country: 'SA',
    description: 'High-throughput biochemistry analyzer, 800 tests/hour. Reagents and consumables included for 3 months of operation. Ideal for medium to large labs.',
    specs: '800 tests/hr, 120 onboard reagents, continuous loading, auto QC, ISE optional.',
    images: '[]',
    status: 'approved',
    sellerName: 'Sara Al-Mutairi',
    sellerEmail: 'sara@labsolutions.sa',
    sellerPhone: '+966545678901',
    sellerCompany: 'Lab Solutions KSA',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Karl Storz Laparoscopy Tower Complete Set',
    category: 'surgical-equipment',
    manufacturer: 'Karl Storz',
    model: 'TELECAM SL II',
    serial: 'KS-LAP-20181122',
    year: 2018,
    condition: 'used',
    warranty: 'none',
    listingType: 'for_sale',
    price: 180000,
    currency: 'SAR',
    payment: 'negotiable',
    location: 'Medina',
    country: 'SA',
    description: 'Complete laparoscopy stack including camera, insufflator, light source, and monitor. All original cables and instruments included. Serviced 2024.',
    specs: 'Full HD camera system, 26003 BA xenon light source, ENDOFLATOR 45L CO2 insufflator.',
    images: '[]',
    status: 'approved',
    sellerName: 'Mohammed Al-Harbi',
    sellerEmail: 'm.harbi@medina-surgical.sa',
    sellerPhone: '+966556789012',
    sellerCompany: 'Medina Surgical Center',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Getinge HS66 Washer-Disinfector',
    category: 'sterilization',
    manufacturer: 'Getinge',
    model: 'HS66',
    serial: 'GT-STER-20220089',
    year: 2022,
    condition: 'used',
    warranty: 'active',
    listingType: 'for_sale',
    price: 55000,
    currency: 'SAR',
    payment: 'bank_transfer',
    location: 'Khobar',
    country: 'SA',
    description: 'Large-capacity washer-disinfector for surgical instruments. In excellent condition — used in private surgical day-care center for 18 months before closure. Full warranty transferable.',
    specs: '2-chamber design, 5 cycles, thermal disinfection A0≥600, 90% water recycling.',
    images: '[]',
    status: 'approved',
    sellerName: 'Nora Al-Qahtani',
    sellerEmail: 'nora@gcc-medical.sa',
    sellerPhone: '+966567890123',
    sellerCompany: 'GCC Medical Supplies',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Looking to Buy: Portable Ultrasound Machine',
    category: 'diagnostic-imaging',
    manufacturer: '',
    model: '',
    serial: '',
    year: null,
    condition: 'new',
    warranty: 'none',
    listingType: 'wanted',
    price: null,
    currency: 'SAR',
    payment: '',
    location: 'Dubai',
    country: 'AE',
    description: 'We are looking for a portable point-of-care ultrasound device with cardiac and abdominal probes. Preferred brands: GE Vscan, Philips Lumify, or Mindray TE7. Budget flexible for the right device.',
    specs: '',
    images: '[]',
    status: 'approved',
    sellerName: 'Dr. Aisha Hussain',
    sellerEmail: 'a.hussain@uaehealthcare.ae',
    sellerPhone: '+971501234567',
    sellerCompany: 'UAE Primary Care Group',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Invacare TDX SP2 Power Wheelchair',
    category: 'rehabilitation',
    manufacturer: 'Invacare',
    model: 'TDX SP2',
    serial: 'INV-REHAB-20210567',
    year: 2021,
    condition: 'refurbished',
    warranty: 'active',
    listingType: 'for_sale',
    price: 12000,
    currency: 'SAR',
    payment: 'cash',
    location: 'Kuwait City',
    country: 'KW',
    description: 'Premium power wheelchair with 4-pole motor and TrueTrack stability system. Refurbished with new batteries, joystick, and upholstery. Perfect for home or clinical use.',
    specs: 'Max speed 10km/h, range 40km, max load 160kg, tilt-in-space seating.',
    images: '[]',
    status: 'approved',
    sellerName: 'Yousef Al-Abdullah',
    sellerEmail: 'y.abdullah@kuwaitrehab.kw',
    sellerPhone: '+96550123456',
    sellerCompany: 'Kuwait Rehab Center',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Siemens Acuson S3000 Ultrasound — For Parts',
    category: 'diagnostic-imaging',
    manufacturer: 'Siemens',
    model: 'Acuson S3000',
    serial: 'SH-US-20150998',
    year: 2015,
    condition: 'parts',
    warranty: 'none',
    listingType: 'for_sale',
    price: 15000,
    currency: 'SAR',
    payment: 'cash',
    location: 'Riyadh',
    country: 'SA',
    description: 'Unit has motherboard failure — selling for parts. Probes (3 linear, 1 convex, 1 phased array) are in excellent working condition and can be sold individually.',
    specs: 'Probes: 18L6 HD, 9L4, 4C1, SC6-1. Consoles, monitor, and keyboard also available.',
    images: '[]',
    status: 'approved',
    sellerName: 'Tech Med Parts',
    sellerEmail: 'sales@techmedparts.sa',
    sellerPhone: '+966512009988',
    sellerCompany: 'Tech Med Parts KSA',
    approvedAt: new Date(),
  },
  {
    ref: ref(),
    name: 'Draeger Evita V500 ICU Ventilator',
    category: 'patient-monitoring',
    manufacturer: 'Draeger',
    model: 'Evita V500',
    serial: 'DR-VENT-20200722',
    year: 2020,
    condition: 'used',
    warranty: 'extendable',
    listingType: 'for_sale',
    price: 145000,
    currency: 'SAR',
    payment: 'bank_transfer',
    location: 'Doha',
    country: 'QA',
    description: 'High-end ICU ventilator with NAVA and NIV modes. Low usage hours — used in COVID overflow ward for 8 months then stored. Full service history. Draeger authorized dealer can verify.',
    specs: 'NAVA, NIV, VCV, PCV, SIMV, Autoflow. Neonatal through adult. NovaStar compressor.',
    images: '[]',
    status: 'pending',
    sellerName: 'Qatar Medical Equipment',
    sellerEmail: 'info@qatarmed.qa',
    sellerPhone: '+97450123456',
    sellerCompany: 'Qatar Medical Equipment LLC',
    approvedAt: null,
  },
];

async function main() {
  console.log('Seeding database...');
  for (const listing of SEED_LISTINGS) {
    await prisma.listing.create({ data: listing }).catch(() => {
      // Skip if ref collision (re-run safety)
    });
  }
  const count = await prisma.listing.count();
  console.log(`Database now has ${count} listings.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
